### ISSUE TITLE
Small bug for Aberdeen North

### ISSUE THREAD

**Issue by Cadair** [Cadair/election-stats#1]
This postcode:
AB24 5QH

centres the map somewhere in the South Atlantic...

**Comment by nabobalis** [comment]
Yes, I saw. I wonder why.

Wonder if it is possible to test it for all constituencies.

**Comment by Cadair** [comment]
I think it is because there is a 'whole' in it (and Aberdeen South). I think just forcing the lat to positive will fix it?

**Comment by nabobalis** [comment]
IT is because some of the co-ordinate arrays are not just one. But have more. So the for loop breaks if that is the case. The result output is a 2x1 array.

So 

``` python

result of for loop = array([ -2.09245298,  57.14277675])
lat = lat[0]
lon = lon[0]
```

Thus wrong.

**Comment by Cadair** [comment]
right... I think... maybe. The code is here: https://github.com/Cadair/election-stats/blob/master/app.py#L45

**Comment by nabobalis** [comment]
Yeah, it is because, the co-ordinates array has two sub arrays. So when it is indexed in the for loop, it loops over the incorrect one. 

Will need an arabian hack.

**Comment by nabobalis** [comment]
Fixed.

**Comment by Cadair** [comment]
I will push it up to heroku when I get my laptop out next.
